#This is makefile for Assignment7


Assignment7: main.o file.o 
	cc main.o file.o -o Assignment7

main.o: main.c file.h 
	cc -c main.c

file.o: file.c file.h 
	cc -c file.c
	
clean:
	rm * o Assignment7	

