#This is makefile for Assignment-5

Assignment5: main.o minheap.o
	cc main.o minheap.o -o Assignment5
main.o: main.c minheap.h
	cc -c main.c 
minheap.o: minheap.c minheap.h
	cc -c minheap.c
clean:
	rm * o Assignment5
